version: '3.8'

services:
  taxi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nyc-taxi-tip-predictor
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped